// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbuufblnzopomikituqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidXVmYmxuem9wb21pa2l0dXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NTkwNDMsImV4cCI6MjA1NTQzNTA0M30.4wRlI4sWFuziitSryVUxf9-J9KfS1YR6Lscy5pTuj_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);